### ISSUE TITLE
1.  Developing the Notes Model

### ISSUE THREAD

**Issue by MVazeZAQ** [MVazeZAQ/MVTeam#1]

**Comment by MVazeZAQ** [comment]
We will use Django for backend.

Please, create env and install django first, than develop notes model.

@Amanidinov, this task is for you

**Comment by Amanidinov** [comment]
> We will use Django for backend.
> 
> Please, create env and install django first, than develop notes model.
> 
> @Amanidinov, this task is for you

I got you)
