### ISSUE TITLE
11.  Creating the "NavBar" Component 

### ISSUE THREAD

**Issue by MVazeZAQ** [MVazeZAQ/MVTeam#11]

**Comment by botirjonshokirov03** [comment]
@Sevval-Ozyurt , bro you have to create Navbar component for our noting app. Just make sure to write clean code as I mentioned,

**Comment by botirjonshokirov03** [comment]
@Sevval-Ozyurt  Today is deadline as we talked before, please create Navbar

**Comment by Sevval-Ozyurt** [comment]
@Botirjon2003  Please look at PR bro
