### ISSUE TITLE
17. Developing the "Note Detail" Page

### ISSUE THREAD

**Issue by MVazeZAQ** [MVazeZAQ/MVTeam#17]

**Comment by botirjonshokirov03** [comment]
@selamsahabe  Did you manage to display details in page from api?

**Comment by selamsahabe** [comment]
yes working on this bro

**Comment by selamsahabe** [comment]
no worries, when I push code, i will let you know

**Comment by selamsahabe** [comment]
No API implemented, just dynamic ui.

**Comment by botirjonshokirov03** [comment]
Okay
