### ISSUE TITLE
19. Connecting Django with React

### ISSUE THREAD

**Issue by MVazeZAQ** [MVazeZAQ/MVTeam#19]

**Comment by botirjonshokirov03** [comment]
@hajiyevmagsud bro use axios or equivant for API

**Comment by hajiyevmagsud** [comment]
okay but first we have to handle backend cors issue, we have to add frontend server url and implement it in backend

**Comment by hajiyevmagsud** [comment]
https://www.stackhawk.com/blog/django-cors-guide/
