### ISSUE TITLE
2.Applying Model Migrations to the Database

### ISSUE THREAD

**Issue by MVazeZAQ** [MVazeZAQ/MVTeam#2]

**Comment by MVazeZAQ** [comment]
@VahidNuraddinov  please do this task, pull the main branch before working on. Keep coding style in our project.

**Comment by VahidNuraddinov** [comment]
> @VahidNuraddinov please do this task, pull the main branch before working on. Keep coding style in our project.

Okay

**Comment by VahidNuraddinov** [comment]
I found [this](https://docs.djangoproject.com/en/5.1/topics/migrations/) helpful
