### ISSUE TITLE
3. Serializing the Notes Model

### ISSUE THREAD

**Issue by MVazeZAQ** [MVazeZAQ/MVTeam#3]

**Comment by MVazeZAQ** [comment]
@hajiyevmagsud  bro do this task

**Comment by hajiyevmagsud** [comment]
okay bro

**Comment by MVazeZAQ** [comment]
Any news? @hajiyevmagsud

**Comment by hajiyevmagsud** [comment]
Yes for sure


> Any news? @hajiyevmagsud

**Comment by hajiyevmagsud** [comment]
I will create different branch and connect to this issue!
