### ISSUE TITLE
4. Building the View for Creating and Retrieving Notes  

### ISSUE THREAD

**Issue by MVazeZAQ** [MVazeZAQ/MVTeam#4]

**Comment by botirjonshokirov03** [comment]
@MVazeZAQ  Thank you for doing so far bro, this issue is for you and I will check it. Good luck)

**Comment by MVazeZAQ** [comment]
> @MVazeZAQ Thank you for doing so far bro, this issue is for you and I will check it. Good luck)

👌🏼
