### ISSUE TITLE
8. Retrieving, Updating, and Deleting Notes

### ISSUE THREAD

**Issue by MVazeZAQ** [MVazeZAQ/MVTeam#8]

**Comment by botirjonshokirov03** [comment]
@hajiyevmagsud this is also for you. Add Get specefic post, Put, and delete url endpoints for later testing postman. Can be fixed later but implement these based on create and get all notes.

**Comment by hajiyevmagsud** [comment]
> @hajiyevmagsud this is also for you. Add Get specefic post, Put, and delete url endpoints for later testing postman. Can be fixed later but implement these based on create and get all notes.

Okay

**Comment by hajiyevmagsud** [comment]
<img width="1342" alt="Screenshot 2024-11-10 at 14 47 32" src="https://github.com/user-attachments/assets/9cfd0f8a-e762-4ddf-8936-4c2b0efc8ca8">
Working on django server, but to check Post request required to check via postman

**Comment by botirjonshokirov03** [comment]
Dont worry bro, it is next job, just push code and create PR as I mentioned
