### ISSUE TITLE
9. Endpoint Testing Using VSCode Postman

### ISSUE THREAD

**Issue by MVazeZAQ** [MVazeZAQ/MVTeam#9]

**Comment by botirjonshokirov03** [comment]
@MVazeZAQ Bro as you django I wan you to check API, endpoints via POSTMAN, if you find bug, please report here. We will fix altogether

**Comment by MVazeZAQ** [comment]
> @MVazeZAQ Bro as you django I wan you to check API, endpoints via POSTMAN, if you find bug, please report here. We will fix altogether

Okay bro
